var CourseMeta;
(function (CourseMeta) {
    (function (runtimeType) {
        runtimeType[runtimeType["no"] = 0] = "no";
        runtimeType[runtimeType["courseNode"] = 1] = "courseNode";
        runtimeType[runtimeType["multiTask"] = 2] = "multiTask";
        runtimeType[runtimeType["product"] = 4] = "product";
        runtimeType[runtimeType["test"] = 8] = "test";
        runtimeType[runtimeType["grammarRoot"] = 16] = "grammarRoot";
        runtimeType[runtimeType["taskCourse"] = 32] = "taskCourse";
        runtimeType[runtimeType["taskPretest"] = 64] = "taskPretest";
        runtimeType[runtimeType["taskPretestTask"] = 128] = "taskPretestTask";
        runtimeType[runtimeType["taskTestInCourse"] = 256] = "taskTestInCourse";
        runtimeType[runtimeType["taskTestSkill"] = 512] = "taskTestSkill";
        runtimeType[runtimeType["ex"] = 1024] = "ex";
        runtimeType[runtimeType["dynamicModuleData"] = 2048] = "dynamicModuleData";
        runtimeType[runtimeType["project"] = 4096] = "project";
        runtimeType[runtimeType["mod"] = 8192] = "mod";
        runtimeType[runtimeType["dynamicTestModule"] = 16384] = "dynamicTestModule";
        runtimeType[runtimeType["skipAbleRoot"] = 32768] = "skipAbleRoot";
        runtimeType[runtimeType["grammar"] = 65536] = "grammar";
        runtimeType[runtimeType["instrs"] = 131072] = "instrs";
        runtimeType[runtimeType["noDict"] = 262144] = "noDict";
        runtimeType[runtimeType["publisher"] = 524288] = "publisher";
        runtimeType[runtimeType["sitemap"] = 1048576] = "sitemap";
        runtimeType[runtimeType["products"] = 2097152] = "products";
        runtimeType[runtimeType["mediaCutFile"] = 4194304] = "mediaCutFile";
        runtimeType[runtimeType["mediaDir"] = 8388608] = "mediaDir";
        runtimeType[runtimeType["error"] = 16777216] = "error";
        runtimeType[runtimeType["testTaskGroup"] = 33554432] = "testTaskGroup";
        runtimeType[runtimeType["multiTest"] = 67108864] = "multiTest";
        runtimeType[runtimeType["multiQuestionnaire"] = 134217728] = "multiQuestionnaire";
        runtimeType[runtimeType["testDemo"] = 268435456] = "testDemo";
        runtimeType[runtimeType["productNew"] = 536870912] = "productNew";
    })(CourseMeta.runtimeType || (CourseMeta.runtimeType = {}));
    var runtimeType = CourseMeta.runtimeType;
    (function (childMode) {
        childMode[childMode["child"] = 0] = "child";
        childMode[childMode["self"] = 1] = "self";
        childMode[childMode["selfChild"] = 2] = "selfChild";
        childMode[childMode["childsWithParent"] = 3] = "childsWithParent";
        childMode[childMode["childsWithParentIfMulti"] = 4] = "childsWithParentIfMulti";
        childMode[childMode["skrivanek_multiTest_std"] = 5] = "skrivanek_multiTest_std";
        childMode[childMode["skrivanek_multiTest_compl"] = 6] = "skrivanek_multiTest_compl";
    })(CourseMeta.childMode || (CourseMeta.childMode = {}));
    var childMode = CourseMeta.childMode;
    (function (dictTypes) {
        dictTypes[dictTypes["unknown"] = 0] = "unknown";
        dictTypes[dictTypes["no"] = 1] = "no";
        dictTypes[dictTypes["L"] = 2] = "L";
    })(CourseMeta.dictTypes || (CourseMeta.dictTypes = {}));
    var dictTypes = CourseMeta.dictTypes;
    (function (testNeeds) {
        testNeeds[testNeeds["no"] = 0] = "no";
        testNeeds[testNeeds["playing"] = 1] = "playing";
        testNeeds[testNeeds["recording"] = 2] = "recording";
    })(CourseMeta.testNeeds || (CourseMeta.testNeeds = {}));
    var testNeeds = CourseMeta.testNeeds;
    CourseMeta.meta = { "rootTagName": "data", "types": { "data": { "props": { "title": {}, "order": { "st": 1088 }, "url": {}, "line": { "enumType": LMComLib.LineIds }, "type": { "enumType": CourseMeta.runtimeType }, "name": {}, "other": {}, "ms": { "st": 64 }, "allLocs": { "st": 1024 }, "styleSheet": { "st": 1024 }, "parent": { "st": 512 }, "uniqId": { "st": 64 }, "Items": {}, "dataItems": { "st": 1536 }, "spaceId": { "st": 1536 }, "globalId": { "st": 1536 }, "style": { "st": 1536 }, "pathParts": { "st": 1024 } } }, "sitemap": { "anc": "data", "props": {} }, "publisher": { "anc": "data", "props": { "vsNetData": { "st": 1024 }, "publisherRoot": { "st": 1024 } } }, "project": { "anc": "data", "props": { "ftpPassword": {}, "FtpUser": {}, "FtpPassword": { "st": 512 } } }, "ptr": { "anc": "data", "props": { "takeChilds": { "enumType": CourseMeta.childMode }, "skip": { "st": 64 }, "take": { "st": 64 }, "urls": {}, "isGramm": { "st": 64 }, "modify": {} } }, "products": { "anc": "data", "props": {} }, "product": { "anc": "data", "props": { "defaultDictType": { "enumType": CourseMeta.dictTypes }, "defaultLocs": {} } }, "taskTestInCourse": { "anc": "data", "props": {} }, "test": { "anc": "data", "props": { "demoTestUrl": {}, "level": {}, "needs": { "enumType": CourseMeta.testNeeds }, "isDemoTest": { "st": 64 } } }, "mod": { "anc": "data", "props": {} }, "taskCourse": { "anc": "data", "props": {} }, "multiTask": { "anc": "data", "props": {} }, "taskTestSkill": { "anc": "data", "props": { "skill": {}, "minutes": { "st": 64 }, "scoreWeight": { "st": 64 } } }, "dynamicModuleData": { "anc": "data", "props": { "groups": {} } }, "testTaskGroup": { "anc": "data", "props": { "urls": {}, "take": { "st": 64 }, "designTitle": {} } }, "ex": { "anc": "data", "props": { "isOldEa": { "st": 1088 }, "isOldEaPassive": { "st": 1088 }, "instrs": { "st": 1024 } } } } };
    CourseMeta.tdata = 'data';
    CourseMeta.tsitemap = 'sitemap';
    CourseMeta.tpublisher = 'publisher';
    CourseMeta.tproject = 'project';
    CourseMeta.tptr = 'ptr';
    CourseMeta.tproducts = 'products';
    CourseMeta.tproduct = 'product';
    CourseMeta.ttaskTestInCourse = 'taskTestInCourse';
    CourseMeta.ttest = 'test';
    CourseMeta.tmod = 'mod';
    CourseMeta.ttaskCourse = 'taskCourse';
    CourseMeta.tmultiTask = 'multiTask';
    CourseMeta.ttaskTestSkill = 'taskTestSkill';
    CourseMeta.tdynamicModuleData = 'dynamicModuleData';
    CourseMeta.ttestTaskGroup = 'testTaskGroup';
    CourseMeta.tex = 'ex';
})(CourseMeta || (CourseMeta = {}));
