//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewData.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDepartment
    {
        public CompanyDepartment()
        {
            this.CompanyDepartments1 = new HashSet<CompanyDepartment>();
            this.CompanyUsers = new HashSet<CompanyUser>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CompanyDepartment> CompanyDepartments1 { get; set; }
        public virtual CompanyDepartment CompanyDepartment1 { get; set; }
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
    }
}
