//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewData.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseData
    {
        public long Id { get; set; }
        public string Key { get; set; }
        public string Data { get; set; }
        public string ShortData { get; set; }
        public int CourseUserId { get; set; }
        public long Date { get; set; }
        public long Flags { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual CourseUser CourseUser { get; set; }
    }
}
