//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewData.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANGMasterScorm
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public long AttemptId { get; set; }
        public string AttemptIdStr { get; set; }
        public Nullable<System.Guid> AttemptIdGuid { get; set; }
        public string Key1Str { get; set; }
        public string Key2Str { get; set; }
        public long Key1Int { get; set; }
        public long Key2Int { get; set; }
        public string Data1 { get; set; }
        public string Data2 { get; set; }
        public long Date { get; set; }
        public byte[] RowVersion { get; set; }
        public int ApiUrlCrc { get; set; }
    }
}
