//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewData.Design
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.CompanyUsers = new HashSet<CompanyUser>();
        }
    
        public long Id { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public System.DateTime Created { get; set; }
        public short VerifyStatus { get; set; }
        public short OtherType { get; set; }
        public string OtherId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Login { get; set; }
        public string LoginEMail { get; set; }
        public long Roles { get; set; }
        public string OtherData { get; set; }
        public Nullable<int> MyPublisherId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<CompanyUser> CompanyUsers { get; set; }
    }
}
