//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGraph
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLicence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyLicence()
        {
            this.UserLicences = new HashSet<UserLicence>();
        }
    
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime Created { get; set; }
        public short Days { get; set; }
        public int LastCounter { get; set; }
        public string ProductId { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLicence> UserLicences { get; set; }
    }
}
