//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGraph
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseUser()
        {
            this.CourseDatas = new HashSet<CourseData>();
            this.UserLicences = new HashSet<UserLicence>();
        }
    
        public int Id { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime HumanAssigned { get; set; }
        public int HumanCompanyUserId { get; set; }
        public string ProductId { get; set; }
        public int UserId { get; set; }
    
        public virtual CompanyUser CompanyUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseData> CourseDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLicence> UserLicences { get; set; }
    }
}
