//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGraph
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLicence
    {
        public int Id { get; set; }
        public int Counter { get; set; }
        public System.DateTime Created { get; set; }
        public int LicenceId { get; set; }
        public System.DateTime Started { get; set; }
        public int UserId { get; set; }
    
        public virtual CompanyLicence CompanyLicence { get; set; }
        public virtual CourseUser CourseUser { get; set; }
    }
}
