//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMComLib.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=pzika-notebook;Initial Catalog=LMComData;Integrated Security=True")]
        public string LMComDataConnectionString {
            get {
                return ((string)(this["LMComDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=77.93.192.50\\MSSQLSERVER,1435;Initial Catalog=lmcomdatatest;Persist S" +
            "ecurity Info=True;User ID=lmcomdatatest;Password=lmcomdatatest")]
        public string lmcomdatatestConnectionString {
            get {
                return ((string)(this["lmcomdatatestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=77.93.192.50\\MSSQLSERVER,1435;Initial Catalog=lmcomdata2;Persist Secu" +
            "rity Info=True;User ID=lmcomdata1;Password=abc123@")]
        public string lmcomdata2ConnectionString {
            get {
                return ((string)(this["lmcomdata2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=q:\\LMCom\\LMCom\\App_Data\\Seo\\Rosetta" +
            "Stone.com.accdb")]
        public string RosettaStone_comConnectionString {
            get {
                return ((string)(this["RosettaStone_comConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("xxx")]
        public string AppDataConnectionString {
            get {
                return ((string)(this["AppDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PZ-ACER-2010\\SQLEXPRESS;Initial Catalog=LMTrados;Integrated Security=" +
            "True")]
        public string LMTradosConnectionString {
            get {
                return ((string)(this["LMTradosConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PZ-ACER-2010\\SQLEXPRESS;Initial Catalog=Rewise;Integrated Security=Tr" +
            "ue")]
        public string RewiseConnectionString {
            get {
                return ((string)(this["RewiseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=195.250.145.24\\MSSQLSERVER,1433;Initial Catalog=lmcomdatatest;Persist" +
            " Security Info=True;User ID=lmcomdatatest;Password=lmcomdatatest")]
        public string lmcomdatatestConnectionString1 {
            get {
                return ((string)(this["lmcomdatatestConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=195.250.145.22\\MSSQLSERVER,1435;Initial Catalog=lmcomdata2;Persist Se" +
            "curity Info=True;User ID=lmcomdatatest;Password=lmcomdatatest")]
        public string lmcomdata2ConnectionString1 {
            get {
                return ((string)(this["lmcomdata2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=195.250.145.22\\MSSQLSERVER,1435;Initial Catalog=lmcomdata2;Persist Se" +
            "curity Info=True;User ID=lmcomdatatest")]
        public string lmcomdata2ConnectionString2 {
            get {
                return ((string)(this["lmcomdata2ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=195.250.145.22\\MSSQLSERVER,1435;Initial Catalog=lmcomdata2;User ID=lm" +
            "comdatatest;Password=lmcomdatatest")]
        public string lmcomdata2ConnectionString3 {
            get {
                return ((string)(this["lmcomdata2ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=195.250.145.24\\MSSQLSERVER,1433;Initial Catalog=lmcomdatatest;User ID" +
            "=lmcomdatatest;Password=lmcomdatatest")]
        public string lmcomdatatestConnectionString2 {
            get {
                return ((string)(this["lmcomdatatestConnectionString2"]));
            }
        }
    }
}
