// <auto-generated />
namespace NewData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class v013 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v013));
        
        string IMigrationMetadata.Id
        {
            get { return "201503061948258_v013"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
